-- Fix membership_registrations table - add ONLY the columns the membership form uses
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS home_phone TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS mobile TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS ministry_name TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS ministry_address TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS residential_address TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS postal_address TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS email TEXT NOT NULL;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS age TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS marital_status TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS divorce_status TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS number_of_children TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS spouse_name TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS spouse_phone TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS years_as_christian TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS called_to_ministry_when TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS church_has_branches TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS number_of_branches TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS ordained_under TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS ordained_when TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS ordained_where TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS affiliated_to_lima TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS want_to_affiliate TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS licensed_with_lima TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS want_to_be_licensed TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS attended_bible_school TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS bible_college_attended TEXT;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS agree_doctrinal BOOLEAN;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS agree_conduct BOOLEAN;
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE membership_registrations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

-- Fix academy_registrations table - add ONLY the columns the academy form uses
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS email TEXT NOT NULL;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS nickname TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS home_phone TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS work_phone TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS place_of_birth TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS age TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS nationality TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS foreign_student TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS country_of_citizenship TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS visa_type TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS passport_number TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS employer TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS employer_address TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS employer_phone TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS marital_status TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS spouse_name TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS spouse_occupation TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS number_of_children TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS children_ages TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS children_at_home TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS parents_born_again TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS parents_approve TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS vision_statement TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS currently_in_high_school TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS high_school_graduate TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS highest_grade_attended TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS last_date_of_attendance DATE;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS previously_applied TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS previously_applied_name TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS transfer_student TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS honors_awards TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS foreign_languages TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS special_skills TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS colleges_attended TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS program_of_study TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS full_time_ministry TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS reason_to_attend TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS how_did_you_hear TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS date_became_christian TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS baptized_by_immersion TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS baptized_holy_spirit TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS seeking_spirit TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS church_member TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS church_name TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS church_denomination TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS church_address TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS senior_pastor TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS church_phone TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS christian_work TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS called_to_ministry TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS called_explanation TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS use_tobacco TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS use_alcohol TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS used_drugs TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS drugs_when TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS denied_admission TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS denied_explanation TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS personal_growth TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS pastor_ref_name TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS pastor_ref_position TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS pastor_ref_church TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS pastor_ref_phone TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS agree_code_of_conduct BOOLEAN;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS application_fee_amount TEXT;
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE academy_registrations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
